spring:
  application:
    name: llm.comparison
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          options:
            model: gemini-3.8-flash
    ollama:
      chat:
        options:
          model: qwen3:1.7b